# version: "3"

volumes:
  db:
    driver: local

services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
    redis:
        restart: on-failure
        image: "redis"
        ports:
          - "6379:6379"
    # back:
    #     restart: on-failure
    #     build:
    #         context: ./nodejs
    Auth:
        restart: on-failure
        build:
            context: ./Auth